export const SET_USERNAME = "SET_USERNAME";
export const GET_USERNAME = "GET_USERNAME";
export const GET_SERVERNAME = "GET_SERVERNAME";
export const SET_ACTIVE_SERVER = "SET_ACTIVE_SERVER";
export const SET_ACTIVE_CHANNEL = "SET_ACTIVE_CHANNEL";
