export const SET_ACTIVE_SERVER = "SET_ACTIVE_SERVER";
export const SET_ACTIVE_CHANNEL = "SET_ACTIVE_CHANNEL";
export const SET_INPUTPANEL_TEXT = "SET_INPUTPANEL_TEXT";
export const SEND_MESSAGE = "SEND_MESSAGE";
