export const SET_ACTIVE_SERVER = "SET_ACTIVE_SERVER";
export const SET_ACTIVE_CHANNEL = "SET_ACTIVE_CHANNEL";
export const SET_INPUTPANEL_TEXT = "SET_INPUTPANEL_TEXT";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SET_CONNECTION_STATUS = "SET_CONNECTION_STATUS";
export const SET_PAGE = "SET_PAGE";
export const SET_SOCKET = "SET_SOCKET";
export const LOGIN = "LOGIN";
